# Timing tests

Seeing which is faster (probably vstack only once).

In [40]:
setup1 = "import numpy; a = numpy.array([i for i in range(1024)]); numpy.random.shuffle(a); emb = []"
setup2 = "import numpy; a = numpy.array([i for i in range(1024)]); numpy.random.shuffle(a); emb = None"

In [34]:
first_way ="""
for i in range(1000):
    emb.append(a)
emb=numpy.vstack([e for e in emb])
emb = []"""
second_way = """
for i in range(1000):
    if emb is not None:
        emb = numpy.vstack((emb,a))
    else:
        emb=a
emb=None"""

In [35]:
import timeit

In [37]:
timeit.timeit(first_way, number=1000, setup=setup1)

1.6925627058371902

In [38]:
timeit.timeit(second_way, number=1000, setup=setup2)
#timeit.timeit('for i in range(1000):\n\tif emb is not None:\n\t\tnumpy.vstack((emb,a))\n\telse:\n\t\temb = a\nemb=None', number=1000, setup='import numpy; a = numpy.array([i for i in range(1024)]); numpy.random.shuffle(a); emb = None')

738.4243913181126

In [25]:
emb1 = []
for i in range(1000):
    emb1.append(a)
emb1=numpy.vstack([e for e in emb1])

emb2=None
for i in range(1000):
    if emb2 is not None:
        emb2 = numpy.vstack((emb2,a))
    else:
        emb2=a


In [39]:
print((emb1==emb2).all())
print(emb1)

True
[[436 641 496 ... 392 315 608]
 [436 641 496 ... 392 315 608]
 [436 641 496 ... 392 315 608]
 ...
 [436 641 496 ... 392 315 608]
 [436 641 496 ... 392 315 608]
 [436 641 496 ... 392 315 608]]
